import Navbar from "../components/navbar/Navbar"
import "./Home.scss"

const Home = () => {
    return (
        <div className="Home">
            <Navbar/>
            <img width="100%" src="https://scontent.fdac116-1.fna.fbcdn.net/v/t1.6435-9/142203541_10158865155432207_3027990041129897325_n.jpg?_nc_cat=104&ccb=1-5&_nc_sid=e3f864&_nc_eui2=AeEFcjx5sayu6w7RLdKYMdBfU9cktecJY55T1yS15wljnmuZYG1brs582YgbWJVCvdU&_nc_ohc=1OlHH7x9JQIAX8_DNEI&_nc_ht=scontent.fdac116-1.fna&oh=7ff12993900bfed64dd2a5f14a09d093&oe=613D5978" alt="" />
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut sapiente facilis atque ipsum maiores mollitia ad autem illo ipsam distinctio dolore molestiae quas aut amet, culpa voluptate delectus! Obcaecati, deleniti.
            Cum et quam fugiat, quae consequuntur, provident maiores saepe soluta fugit voluptatem adipisci suscipit eum. Ab deserunt, minus repellat qui corporis officia odio obcaecati, velit molestias maiores ipsum similique ipsa!
            Necessitatibus maiores praesentium nesciunt, quidem asperiores ratione et nam sit laborum rerum ipsum corporis voluptas, iusto consectetur saepe maxime tempore deserunt commodi quia eligendi cum perspiciatis. Ab eos rem recusandae!
            Dicta facilis assumenda exercitationem harum ea architecto quaerat praesentium eius iste, recusandae libero animi nisi sit quos amet pariatur enim non. Nihil expedita eius ratione quis necessitatibus vero sapiente labore!
            Architecto quaerat cupiditate omnis ut nobis nihil adipisci hic, doloremque praesentium rerum sunt aperiam repellat quis voluptatum, non molestiae aut cumque! Ut est saepe voluptatum unde doloribus temporibus non ipsum.
            Perspiciatis libero vel facilis quod nostrum reprehenderit ipsum, recusandae voluptates. Corporis maxime animi, eius odio deserunt voluptatibus error neque vitae eaque voluptatum, dignissimos omnis impedit. Iusto labore est voluptatibus illum.
            Debitis nihil magni inventore praesentium et veritatis quidem quod fugiat labore, provident neque veniam repudiandae at blanditiis ad rem earum amet totam iure. Officia aliquid porro blanditiis cupiditate ullam molestias.
            Quae atque incidunt esse facilis eligendi dolorum perspiciatis facere veritatis quo, iusto sint cum ipsam sapiente quos aperiam quam praesentium ullam. Magnam molestias est optio unde officiis nisi sit laboriosam.
            Doloribus rerum laborum, laboriosam molestiae alias inventore debitis aliquid omnis velit, reiciendis incidunt voluptatem facilis, esse amet voluptatum? Similique, ducimus illo? Necessitatibus error sit obcaecati pariatur natus culpa nihil odio.
            Consequuntur dolores, assumenda labore repudiandae incidunt adipisci maxime rerum hic excepturi porro fuga voluptatibus ratione numquam similique aut omnis quibusdam quisquam odit quidem inventore delectus soluta. Delectus impedit odio mollitia!
            Fuga fugiat reprehenderit molestias, alias unde quam facere enim ad. Commodi labore sunt totam quos dicta? Voluptatibus, officiis molestiae enim labore sunt dolore soluta laboriosam ab. Expedita culpa excepturi rerum!
            Nulla, aliquam neque tenetur culpa nobis dolor veritatis magni asperiores sit, perferendis maxime corrupti distinctio blanditiis est dignissimos vitae sunt repellat libero voluptatem? Doloribus consequuntur ipsam maiores repellendus ipsa iste!
            Obcaecati ad blanditiis, natus ipsum, eveniet aliquam placeat, distinctio ex nesciunt quia commodi eos repudiandae aspernatur! Earum, ad magni unde error ratione et ea. Ratione, ea? Quas consectetur sint non!
            Quasi perferendis adipisci quidem porro eos, cupiditate, iure modi inventore vero debitis necessitatibus veritatis amet autem illo, ipsam obcaecati cum? Repellendus iusto illum tempora qui incidunt id architecto corrupti dignissimos.
            Possimus eveniet incidunt expedita vero eos sed minus accusantium nostrum sint, quos perspiciatis repellat maiores quibusdam illum voluptatum aliquam. Ea doloremque sit, sint beatae porro voluptas eligendi repellat inventore libero.
            Nesciunt quasi nam voluptas molestiae magnam blanditiis amet illo perferendis numquam ipsum deleniti minus nihil obcaecati eligendi nulla vitae, magni laboriosam minima aliquam voluptate quis laudantium cumque totam neque! Ut!
            Cupiditate facilis fuga ipsam et sequi optio. Tenetur magnam facilis aspernatur autem in ab cupiditate vitae eligendi quos numquam perferendis possimus iure nostrum, quis fuga natus voluptas dignissimos ipsum veniam.
            Cumque magni sunt officiis dolorem? Laboriosam voluptatem corrupti expedita! Vel id laborum obcaecati iusto. Rem nobis error eligendi atque vel eum, dignissimos quasi sapiente molestias illum deleniti quibusdam adipisci cupiditate?
            Culpa, cumque! Distinctio ducimus in, veritatis incidunt eaque consequatur illum recusandae laudantium saepe nulla fuga consequuntur molestiae est amet odit tempore ratione quod natus possimus adipisci ipsa asperiores vel sequi!
            Exercitationem incidunt ipsa quos nemo dolorum error nulla tempora quo, nostrum blanditiis dolores ex atque consectetur reprehenderit ducimus optio eos est reiciendis tenetur voluptatum! Necessitatibus nulla dolorem quia. Cum, ipsum.
            Repudiandae odit distinctio, numquam minima autem corrupti! Officiis culpa possimus minima ea fugit cupiditate ipsum architecto maxime totam corporis aliquam ullam, harum placeat tempora facere reprehenderit? Molestiae aspernatur velit optio?
            Vel, repellat praesentium minima alias nobis, qui consequuntur laboriosam dolor delectus optio cum in, doloribus veritatis fugit corrupti porro cupiditate ipsum sequi tenetur adipisci explicabo quasi. Optio blanditiis fugiat laudantium!
            Quaerat nobis aut, consequatur officia vitae, ipsa est itaque, enim qui alias dolor quae cumque ex. Perferendis fuga debitis consequuntur, asperiores numquam porro nisi harum ipsum aliquid magnam eveniet eos.
            Ipsam eligendi placeat ipsum molestias, commodi repellendus aspernatur architecto doloribus facere unde non cumque iste quos, repellat magni! Alias velit obcaecati dicta numquam quod itaque nostrum aliquid tempora nemo ipsum.
            Enim incidunt quos animi sit voluptatum minus eos nihil iure hic consequatur ut libero dolorem inventore minima pariatur, dolor delectus. Vel expedita vitae accusantium laudantium. Quisquam sint nemo commodi vero.
            Nobis et corrupti laudantium suscipit commodi eligendi culpa iure dolorum earum temporibus odit nulla placeat quos at provident minima, ut nostrum voluptatibus sed reiciendis ipsam repellendus qui reprehenderit illo. Alias?
            Excepturi autem vero perferendis accusamus delectus quia! Cupiditate provident recusandae sint voluptate consequatur consectetur nostrum, molestiae iure sit magni deleniti repellendus quae quia. Ex ipsa illo rerum doloribus, quasi perferendis.
            Velit doloremque fugiat voluptatem ex asperiores dignissimos nostrum neque impedit molestiae at obcaecati quae suscipit est ullam, nulla aspernatur, magni culpa non reiciendis! Aliquam illo distinctio autem. Expedita, doloremque nam!
            Quod nisi laudantium, nesciunt doloremque sequi explicabo in eius fugiat non libero iste adipisci officiis tenetur labore quis necessitatibus dolorem ut quibusdam. Suscipit quos, perspiciatis deserunt quisquam provident voluptatibus placeat?
            Sapiente ducimus nihil rem delectus a repellat enim ipsum eaque, perferendis excepturi harum qui culpa quia exercitationem velit natus quaerat dolore minus quisquam veniam maxime id voluptas? Officia, in officiis?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus molestiae maiores minima quisquam eaque quas id explicabo itaque molestias corrupti sapiente saepe, adipisci voluptates repellendus quis autem modi, ipsam officia?
            Amet magnam commodi fugit repudiandae nesciunt, ipsa impedit. Nam impedit dolore laborum beatae animi delectus cupiditate molestiae. Unde omnis, illum nihil neque dolor quos quo voluptatum corrupti optio aut alias?
            Sint in totam vel delectus pariatur vitae debitis ab accusantium, repudiandae, libero incidunt ut saepe labore qui iure ex aliquid quos quo enim. Repudiandae aut harum, consequatur libero quam cupiditate!
            Maiores temporibus exercitationem aliquam dicta praesentium dolores ea hic ipsa saepe, excepturi commodi cumque! Ea illo quo esse doloribus? Magnam nesciunt voluptate voluptas eum commodi tempore nam ducimus nobis consectetur!
            Architecto autem repellendus dignissimos suscipit cumque possimus corporis. Est veritatis totam nemo quos perferendis possimus ratione, nihil consequatur molestiae sint fugit nesciunt doloremque natus molestias amet vitae earum laborum repellendus.
            Sunt mollitia quam praesentium et illo nostrum fugiat consequatur? Quibusdam mollitia magnam vitae aperiam vel adipisci quod, possimus laborum eius excepturi amet cumque omnis sunt beatae a quos neque nostrum.
            Laboriosam commodi sed iusto modi quos incidunt omnis reiciendis voluptate. Ullam minima sunt ea et hic, harum aperiam a molestias illum incidunt ipsa vel illo sint, voluptatum, aut molestiae exercitationem.
            Nobis ab consectetur accusantium quae fugit officiis nisi mollitia! Quo dolores modi itaque? Distinctio quae labore pariatur molestias quos. Vitae, eligendi omnis sunt dolor voluptas possimus quos voluptatum culpa fugit?
            Magni sapiente ea hic fugit doloremque fuga laboriosam impedit at esse eius numquam assumenda velit id modi, accusantium ab! Quibusdam maxime provident, earum quae atque consequuntur officia molestias repellendus illo?
            Commodi, necessitatibus. Quisquam a veniam unde commodi iure ullam, odio iusto optio pariatur illo quasi neque fugiat. Deleniti eius vel architecto, earum eos sit distinctio quo eveniet est fuga praesentium.
            Ut minima eum dolores vel quos magnam doloribus cum qui sapiente ab totam quisquam id veniam, molestias sunt. Explicabo rerum a consequuntur illo debitis distinctio deserunt eius autem rem perspiciatis.
            Illum consequatur sapiente minus quam reiciendis nostrum explicabo illo adipisci quia, vel natus exercitationem consequuntur ea distinctio tempore voluptatem et sequi quos cumque eligendi. Suscipit, beatae! Fugit maxime rem obcaecati?
            Amet architecto perspiciatis ut ducimus molestias dolorum neque vel dolore delectus totam aliquid exercitationem repudiandae quas vero eveniet quidem atque aspernatur necessitatibus, sapiente odio pariatur sed similique, doloremque voluptatem. Expedita.
            In at voluptatibus optio asperiores, eius eligendi repudiandae quas eaque minus nostrum porro itaque hic corrupti libero inventore reprehenderit ad sit fugiat vero sed sunt rem. Corrupti veritatis perspiciatis facilis.
            Quasi qui eveniet, laboriosam at asperiores illo praesentium ipsum veritatis molestias provident voluptas dolore doloremque autem totam voluptatem! Iusto quia eveniet explicabo, earum voluptatibus aspernatur saepe amet atque quibusdam veniam!
            Doloribus corrupti illo aliquam error minus ullam temporibus sit officia nesciunt suscipit nostrum praesentium eligendi vel deserunt qui modi id dolorum quidem numquam, quia similique? Beatae praesentium officia doloremque cupiditate!
            Ullam optio molestiae officiis quaerat. Veniam voluptatem, excepturi dignissimos sit praesentium officia reprehenderit vel fugiat delectus cupiditate fuga in debitis sapiente dolorem incidunt tempora dolore sunt repellendus laboriosam, tenetur similique.
            Blanditiis minus dolores ipsum, ut magni corrupti. Ducimus quasi, dolor ab repudiandae veniam atque accusamus architecto eius. Fuga perferendis esse repudiandae deleniti corporis aliquam, laboriosam iure reiciendis quibusdam hic iste!
            Tempore, ullam neque nemo, excepturi vitae iusto esse dolore repellendus quos alias laudantium impedit beatae. Iure ea cumque et magni quibusdam. Cupiditate dolore repudiandae qui id porro, libero assumenda in?
            Veritatis, reprehenderit quasi! In eum tempora accusantium perferendis quae consequuntur inventore necessitatibus molestias et omnis, minus nulla pariatur. Laborum obcaecati hic earum dicta repellat. Inventore ullam quos quam ipsam culpa!
            Assumenda laboriosam voluptatem nisi! Modi laboriosam veniam dolore quibusdam aliquid corporis possimus nobis necessitatibus. Blanditiis quo ad, pariatur exercitationem, possimus vel commodi numquam provident voluptatem at vero quod in porro!
            Voluptas, atque optio perferendis mollitia assumenda blanditiis sunt dolorum quasi ducimus earum error nulla, ex temporibus omnis dignissimos aspernatur iusto harum explicabo cupiditate iste cum doloribus? Eligendi soluta unde reprehenderit.
            Suscipit quibusdam illum sint porro numquam laborum quas quis cupiditate voluptas similique rerum reprehenderit, tempora laudantium. Animi unde porro sint corporis dignissimos recusandae quia dolores reiciendis odio, dolorem beatae nisi.
            Cum placeat officiis, dolorem vel illo suscipit fugiat aspernatur autem in corrupti esse necessitatibus ex sunt tempore recusandae optio officia a perferendis tenetur enim, repudiandae ea ipsum. Autem, ea illo?
            Doloremque ducimus adipisci iusto quibusdam, voluptatibus sunt eos harum eum quas tenetur cupiditate provident ullam recusandae laboriosam facilis voluptatum odit aspernatur id. Similique nemo maxime veritatis nulla animi aperiam accusamus.
            Aspernatur consectetur nemo, aliquid et optio amet modi repellat soluta ratione sed voluptatem, ea deserunt voluptatum ex velit ab quod ad minus! Blanditiis ex officiis obcaecati? Enim quisquam modi quo.
            Itaque, perspiciatis doloribus. Optio eveniet error autem ratione ducimus excepturi, cumque ab omnis. Saepe sapiente, repellat veniam culpa, assumenda nisi maiores debitis iure voluptatum suscipit voluptas maxime accusamus! Voluptatem, enim?
            Ducimus architecto exercitationem sit consectetur dolores necessitatibus reprehenderit eos ipsum facilis officia alias nulla sint laborum vero, in recusandae voluptatum incidunt. Et esse ipsa dolorem perferendis illo rem sequi ut!
            Qui odit obcaecati quam animi corporis ea voluptate voluptates harum. Atque omnis aut sed nobis fugit quia. Incidunt praesentium in recusandae aliquid inventore pariatur veniam, consequatur perferendis adipisci dolores aperiam.
            Dolor, suscipit enim tempora magnam ducimus sit quasi est laudantium animi quas quam, numquam assumenda quod sequi fugiat totam autem. A cum sunt ducimus numquam voluptates odit nihil modi beatae!
        </div>
    )
}

export default Home
